version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/khav
      SPRING_DATASOURCE_USERNAME: khavkivar
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - db

  db:
    container_name: postgres-spring-boot
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-khavkivar} -d ${POSTGRES_DB:-khav}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      POSTGRES_USER: khavkivar
      POSTGRES_PASSWORD: password
      POSTGRES_DB: khav
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
